# coding: utf-8


INCHES_TO_CENTIMETERS_FACTOR = 2.54
METERS_TO_FEET_FACTOR = 3.28084
KILOGRAMS_TO_POUNDS_FACTOR = 2.20462

CENTIMETERS_TO_INCHES_FACTOR = 1 / INCHES_TO_CENTIMETERS_FACTOR
FEET_TO_METERS_FACTOR = 1 / METERS_TO_FEET_FACTOR
POUNDS_TO_KILOGRAMS_FACTOR = 1 / KILOGRAMS_TO_POUNDS_FACTOR

MAX_MANTISSA_LENGTH = 3
